let redPurple = document.getElementsByClassName('redPurple')
console.log(redPurple)
let redPurpleAll = document.querySelectorAll('.redPurple')
console.log(redPurpleAll)
let classRedPurple = document.querySelectorAll("h1.redPurple")
console.log(classRedPurple)
let pack = document.querySelectorAll("li,p,span")
console.log(pack)
let important = document.querySelectorAll("li.important,p")
console.log(important)
let fin = document.querySelectorAll('h1.redPurple,span.redPurple')
console.log(fin)
